### ISSUE TITLE
Program dosnt search a yt live

### ISSUE THREAD

**Issue by k0ssa** [xfreed/Youtube-Viewers#2]
When i apply a yt live link ex. https://www.youtube.com/watch?v=-RrKQVCbYQI the "Title" is showing connecting and after few sec is gone and only errors are counting
![Zrzut ekranu 2021-05-13 085052](https://user-images.githubusercontent.com/22254666/118089370-8a4c0100-b3c8-11eb-9c84-8955becbfd39.png)

**Comment by xfreed** [comment]
Hi, are you tring "-RrKQVCbYQI" or only "RrKQVCbYQI"?
The correct one is "-RrKQVCbYQI".
