### ISSUE TITLE
many errors

### ISSUE THREAD

**Issue by RicardPort** [xfreed/Youtube-Viewers#3]
hello,
 I have connections but very slowly I have a private s5 proxy with ipvanish it only reaches 140 viewers (connections), then half disappears and another appears, and at a friend's it reaches 500/2000 viewers. Is it the fault of the internet?

**Comment by xfreed** [comment]
Hi, this problem can be due to poor internet and weak computer characteristics, have you tried to run the program somewhere other than your friend's computer with your proxy list?

**Comment by RicardPort** [comment]
yes I ran it on ssh (vps) and it's better, tell me if you can convert this script to Twitch?

**Comment by xfreed** [comment]
In the future - yes. But, now I don't have much time.
