### ISSUE TITLE
Doesn't work anymore, would you be so kind to update? 

### ISSUE THREAD

**Issue by lizuca1** [xfreed/Youtube-Viewers#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xfreed** [comment]
Tested, for me program work normal, what error do you get?

**Comment by githubtrip** [comment]
Yeah, not working. Views not increasing.

**Comment by lizuca1** [comment]
I don't get a specific error, it's just the views not increasing on youtube.

**Comment by xfreed** [comment]
Do you use your proxy or that program have?
