### ISSUE TITLE
the program closes during execution

### ISSUE THREAD

**Issue by Elexinus** [xfreed/Youtube-Viewers#5]
![cats](https://user-images.githubusercontent.com/94555141/142295004-7bfd7f64-f772-4192-9edb-8e59a735fc5f.jpg)

when the program runs it closes...

help me please

thks

**Comment by xfreed** [comment]
Hi @Elexinus !

Is it crash in the start or when you input some data?

Please provide more information on what step program crash:
1. After starting
2. After entering video ID
3. After entering thread count
4. After picking proxy

Also, it will be great if you send me exception code by text.
